import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "react-hot-toast";
import ToasterProvider from "@/components/providers/toastProvider";
import  getCurrentUser  from "@/actions/getCurrentUser";
import Navabr from "@/components/Navabr";
import ModelProvider from "@/components/providers/ModelProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Photography Showcase",
  description: "Generated by create next app",
};
export const dynamic = "force-dynamic"

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser()
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider             attribute="class"
            defaultTheme="system"
            enableSystem>
          <ToasterProvider />
          <ModelProvider />
          <Navabr currentUser={currentUser} />
           {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
